package au.edu.unsw.soacourse.greenslip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-25T18:27:31.215+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://greenslip.soacourse.unsw.edu.au", name = "BPELGreenSlipService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BPELGreenSlipService {

    @WebResult(name = "GSCheckResponse", targetNamespace = "http://greenslip.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(operationName = "GSCheck", action = "http://greenslip.soacourse.unsw.edu.au/GSCheck")
    public GSCheckResponse gsCheck(
        @WebParam(partName = "parameters", name = "GSCheckRequest", targetNamespace = "http://greenslip.soacourse.unsw.edu.au")
        GSCheckRequest parameters
    ) throws GSCheckFaultMsg;
}
