package au.edu.unsw.soacourse.greenslip;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-25T18:27:31.219+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "BPELGreenSlipService", 
                  wsdlLocation = "file:/D:/Luna%20Eclipse%20WS/BPELProcessService/src/main/resources/wsdl/BPELGreenSlipService.wsdl",
                  targetNamespace = "http://greenslip.soacourse.unsw.edu.au") 
public class BPELGreenSlipService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://greenslip.soacourse.unsw.edu.au", "BPELGreenSlipService");
    public final static QName BPELGreenSlipServiceSOAP = new QName("http://greenslip.soacourse.unsw.edu.au", "BPELGreenSlipServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Luna%20Eclipse%20WS/BPELProcessService/src/main/resources/wsdl/BPELGreenSlipService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BPELGreenSlipService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Luna%20Eclipse%20WS/BPELProcessService/src/main/resources/wsdl/BPELGreenSlipService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BPELGreenSlipService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BPELGreenSlipService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BPELGreenSlipService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BPELGreenSlipService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BPELGreenSlipService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BPELGreenSlipService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BPELGreenSlipService
     */
    @WebEndpoint(name = "BPELGreenSlipServiceSOAP")
    public BPELGreenSlipService getBPELGreenSlipServiceSOAP() {
        return super.getPort(BPELGreenSlipServiceSOAP, BPELGreenSlipService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELGreenSlipService
     */
    @WebEndpoint(name = "BPELGreenSlipServiceSOAP")
    public BPELGreenSlipService getBPELGreenSlipServiceSOAP(WebServiceFeature... features) {
        return super.getPort(BPELGreenSlipServiceSOAP, BPELGreenSlipService.class, features);
    }

}
