
package au.edu.unsw.soacourse.greenslip;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-25T18:27:31.212+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "GSCheckFault", targetNamespace = "http://greenslip.soacourse.unsw.edu.au")
public class GSCheckFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.greenslip.ServiceFaultType gsCheckFault;

    public GSCheckFaultMsg() {
        super();
    }
    
    public GSCheckFaultMsg(String message) {
        super(message);
    }
    
    public GSCheckFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public GSCheckFaultMsg(String message, au.edu.unsw.soacourse.greenslip.ServiceFaultType gsCheckFault) {
        super(message);
        this.gsCheckFault = gsCheckFault;
    }

    public GSCheckFaultMsg(String message, au.edu.unsw.soacourse.greenslip.ServiceFaultType gsCheckFault, Throwable cause) {
        super(message, cause);
        this.gsCheckFault = gsCheckFault;
    }

    public au.edu.unsw.soacourse.greenslip.ServiceFaultType getFaultInfo() {
        return this.gsCheckFault;
    }
}
