
package au.edu.unsw.soacourse.pinkslip;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-27T02:22:00.950+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "PSCheckFault", targetNamespace = "http://pinkslip.soacourse.unsw.edu.au")
public class PSCheckFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.pinkslip.ServiceFaultType psCheckFault;

    public PSCheckFaultMsg() {
        super();
    }
    
    public PSCheckFaultMsg(String message) {
        super(message);
    }
    
    public PSCheckFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PSCheckFaultMsg(String message, au.edu.unsw.soacourse.pinkslip.ServiceFaultType psCheckFault) {
        super(message);
        this.psCheckFault = psCheckFault;
    }

    public PSCheckFaultMsg(String message, au.edu.unsw.soacourse.pinkslip.ServiceFaultType psCheckFault, Throwable cause) {
        super(message, cause);
        this.psCheckFault = psCheckFault;
    }

    public au.edu.unsw.soacourse.pinkslip.ServiceFaultType getFaultInfo() {
        return this.psCheckFault;
    }
}
