
package au.edu.unsw.soacourse.pinkslip;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-27T02:22:00.897+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "VehicleAgeFault", targetNamespace = "http://pinkslip.soacourse.unsw.edu.au")
public class VehicleAgeFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.pinkslip.ServiceFaultType vehicleAgeFault;

    public VehicleAgeFaultMsg() {
        super();
    }
    
    public VehicleAgeFaultMsg(String message) {
        super(message);
    }
    
    public VehicleAgeFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VehicleAgeFaultMsg(String message, au.edu.unsw.soacourse.pinkslip.ServiceFaultType vehicleAgeFault) {
        super(message);
        this.vehicleAgeFault = vehicleAgeFault;
    }

    public VehicleAgeFaultMsg(String message, au.edu.unsw.soacourse.pinkslip.ServiceFaultType vehicleAgeFault, Throwable cause) {
        super(message, cause);
        this.vehicleAgeFault = vehicleAgeFault;
    }

    public au.edu.unsw.soacourse.pinkslip.ServiceFaultType getFaultInfo() {
        return this.vehicleAgeFault;
    }
}
